<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title> 
    <script>

    // 1. Declare variables using var, let, and const
    

            var name = "Deebak";
            let age = 22;

            const country = "India";
            console.log(name);
            console.log(age);
            console.log(country);
            

    // 2. Different data types


        let studentName = "Deebak";      
        let marks = 85;                 
        let isPassed = true;           
        let result = null;              
        let address;

        console.log(studentName);
        console.log(marks);
        console.log(isPassed);
        console.log(result);
        console.log(address);


    // 3. Arithmetic operators


        let a = 10;
        let b = 3;

        console.log(a + b);   
        console.log(a - b);  
        console.log(a * b);   
        console.log(a / b);  
        console.log(a % b);   

    // 4. Comparison operators


        console.log(10 == "10");    
        console.log(10 === "10"); 


    // 5. Logical operators


        let x = true;
        let y = false;

        console.log(x && y);  
        console.log(x || y);

           
    </script>

</head>
<body>

    <h1>Welcome To Page</h1>

</body>
</html>
