<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>

    // Task 1   


                // let num = 10;
                // if (num > 0) {
                //     console.log("Positive");
                // } else if (num < 0) {
                //     console.log("Negative");
                // } else {
                //     console.log("Zero");
                // }

    // Task 2

            // let num = 7;
            // if (num % 2 == 0) {
            //     console.log("Even");
            // } else {
            //     console.log("Odd");
            // }


    // Task 3 


        // let age = 20;
        // if (age >= 18) {
        //     console.log("Eligible to vote");
        // } else {
        //     console.log("Not eligible to vote");
        // } 

    // Task 4


        // let a = 25;
        // let b = 15;
        // if (a > b) {
        //     console.log(a + " is largest");
        // } else {
        //     console.log(b + " is largest");
        // } 


    // Task 5

        // let marks = 85;
        // if (marks >= 90) {
        //     console.log("Grade A+");
        // } else if (marks >= 80) {
        //     console.log("Grade A");
        // } else if (marks >= 70) {
        //     console.log("Grade B");
        // } else if (marks >= 60) {
        //     console.log("Grade C");
        // } else if (marks >= 50) {
        //     console.log("Grade D");
        // } else {
        //     console.log("Fail");
        // } 

    // Task 6

        // let a = 25;
        // let b = 40;
        // let c = 30;
        // if (a > b && a > c) {
        //     console.log(a + " is largest");
        // } else if (b > a && b > c) {
        //     console.log(b + " is largest");
        // } else {
        //     console.log(c + " is largest");
        // }

    // Task 7  

        // let year = 2024;
        // if (year % 400 == 0 || (year % 4 == 0 && year % 100 != 0)) {
        //     console.log("Leap year");
        // } else {
        //     console.log("Not a leap year");
        // } 

    // Task 8

        // let age = 20;
        // if (age >= 18) {
        //     console.log("Eligible for driving license");
        // } else {
        //     console.log("Not eligible for driving license");
        // }

    // Task 9

        // let num = 30;
        // if (num % 3 == 0 && num % 5 == 0) {
        //     console.log("Divisible by both 3 and 5");
        // } else {
        //     console.log("Not divisible by both 3 and 5");
        // } 

    // Task 10

        // let a = 20;
        // let b= 5;
        // let operator = "*";
        // if (operator == "+") {
        //     console.log(a + b);
        // } else if (operator == "-") {
        //     console.log(a - b);
        // } else if (operator == "*") {
        //     console.log(a * b);
        // } else if (operator == "/") {
        //     console.log(a / b);
        // } else {
        //     console.log("Invalid operator");
        // }



    </script>

</head>
<body>

    <h1>Welcome to page</h1>

</body>
</html>
